### Project specific config ###
install:
  - set PATH=C:\Ruby23-x64\bin;%PATH%
  - ruby --version

environment:
  matrix:
  - ATOM_CHANNEL: stable
  - ATOM_CHANNEL: beta

### Generic setup follows ###
build_script:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/atom/ci/master/build-package.ps1'))

branches:
  only:
    - master

version: "{build}"
platform: x64
clone_depth: 10
skip_tags: true
test: off
deploy: off
